name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build, lint, and test
        run: ./gradlew lint testDebugUnitTest assembleDebug --stacktrace

      - name: Upload debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: crowdtracker-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
